### ISSUE TITLE
Issue Importing Transactions?

### ISSUE THREAD

**Issue by cclandau** [b3devs/MojitoLib#1]
I get this issue when I try importing transaction data. Any idea what I can do to fix this? 
Exception: UiApp has been deprecated. Please use HtmlService instead.

**Comment by b3devs** [comment]
I discovered this same issue Thursday night. Google no longer supports the
method I was using to display dialog windows in Mojito. I started working
on fixing it this weekend, but there are several dialog windows I have to
rewrite. Hopefully I'll be done by Sunday night.

-b3
